name: beam_PreCommit_Website_Stage_GCS

on:
  push:
    tags: ['v*']
    branches: ['master', 'release-*']
    paths: ['website/**']
  pull_request_target:
    #branches: ['master', 'release-*']
    paths: ['website/**']
  issue_comment:
    types: [created]
  schedule:
    - cron: '* */6 * * *'
#Setting explicit permissions for the action to avoid the default permissions which are `write-all` in case of pull_request_target event
permissions:
  actions: write
  pull-requests: read
  checks: read
  contents: read
  deployments: read
  id-token: none
  issues: read
  discussions: read
  packages: read
  pages: read
  repository-projects: read
  security-events: read
  statuses: read

jobs:
    beam_PreCommit_Website_Stage_GCS:
      if: |
        github.event_name == 'push' || 
        github.event_name == 'pull_request_target' || 
        github.event.comment.body == 'Run Website_Stage_GCS PreCommit' || 
        github.event_name == 'schedule'
      runs-on: [self-hosted, ubuntu-20.04]
      name: beam_PreCommit_Website_Stage_GCS
      steps:
        - name: Git checkout
          uses: actions/checkout@v3
          with:
            ref: ${{ github.event.pull_request.head.sha }}
        - name: Rerun on comment
          if: github.event.comment.body == 'Run Website_Stage_GCS PreCommit'
          uses: ./.github/actions/rerun-job-action
          with:
            pull_request_url: ${{ github.event.issue.pull_request.url }}
            github_repository: ${{ github.repository }}
            github_token: ${{ secrets.GITHUB_TOKEN }}
            github_job: ${{ github.job }}
            github_current_run_id: ${{ github.run_id }}
        - name: Install Java
          uses: actions/setup-java@v3.8.0
          with:
            distribution: 'zulu'
            java-version: '8'
        - name: Setup Gradle
          uses: gradle/gradle-build-action@v2
          with:
            cache-read-only: false
        - name: Install Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.8'
        - name: Set up Cloud SDK
          uses: google-github-actions/setup-gcloud@v1
        - name: run website_stageWebsite script
          run: ./gradlew :website:stageWebsite