# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: beam_PreCommit_GoPortable

on:
    push:
        tags: ['v*']
        branches: ['master', 'release-*']
        paths: ['model/**', 'sdks/go.**', 'release/**']
    pull_request:
        branches: ['**']
        # branches: ['master', 'release-*']
        paths: ['model/**', 'sdks/go.**', 'release/**']
    issue_comment:
        types: [created]
    schedule:
        - cron: '* */6 * * *'

jobs:
  beam_PreCommit_GoPortable:
    if: |
      github.event_name == 'push' || 
      github.event_name == 'pull_request' || 
      github.event.comment.body == 'Run GoPortable PreCommit' || 
      github.event_name == 'schedule'
    runs-on: [self-hosted, ubuntu-20.04, main]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Rerun on comment
        if: github.event.comment.body == 'Run GoPortable PreCommit'
        uses: ./.github/actions/rerun-job-action
        with:
          pull_request_url: ${{ github.event.issue.pull_request.url }}
          github_repository: ${{ github.repository }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_job: ${{ github.job }}
          github_current_run_id: ${{ github.run_id }}
      - name: Setup self-hosted
        uses: ./.github/actions/setup-self-hosted-action
        with:
          requires-py-37: false
          requires-py-39: false
          requires-java-8: false
          requires-go: false
      - name: run goPortablePreCommit script
        run: ./gradlew :goPortablePreCommit -Pdocker-pull-licenses