name: beam_PreCommit_Website

on:
  push:
    tags: ['v*']
    branches: ['master', 'release-*']
  pull_request:
    branches: ['master', 'release-*']
    paths: ['website/**']
  issue_comment:
    types: [created]
  schedule:
    - cron: '* */6 * * *'

jobs:
    beam_PreCommit_Website:
        if: ${{github.event.issue.pull_request}} || ${{github.event.comment.body == 'Run Website PreCommit'}} || ${{github.event.schedule}}
        runs-on: [self-hosted, ubuntu-20.04]
        name: beam_PreCommit_Website
        steps:       
          - name: Git checkout
            uses: actions/checkout@v3
          - name: Install Java
            uses: actions/setup-java@v3.8.0
            with:
              distribution: 'zulu'
              java-version: '8'
          - name: Setup Gradle
            uses: gradle/gradle-build-action@v2
            with:
              cache-read-only: false
          - name: run websitePreCommit script
            run: ./gradlew :websitePreCommit