name: beam_PreCommit_Website_Stage_GCS

on:
  push:
    tags: ['v*']
    branches: ['master', 'release-*']
    paths: ['website/**']
  pull_request_target:
    #branches: ['master', 'release-*']
    paths: ['website/**']
  issue_comment:
    types: [created]
  schedule:
    - cron: '* */6 * * *'

jobs:
    beam_PreCommit_Website_Stage_GCS:
        if: ${{github.event.issue.pull_request}} || ${{github.event.comment.body == 'Run Website_Stage_GCS PreCommit'}} || ${{github.event.schedule}}
        runs-on: [self-hosted, ubuntu-20.04]
        name: beam_PreCommit_Website_Stage_GCS
        steps:
          - name: Git checkout
            uses: actions/checkout@v3
          - name: Install Java
            uses: actions/setup-java@v3.8.0
            with:
              distribution: 'zulu'
              java-version: '8'
          - name: Setup Gradle
            uses: gradle/gradle-build-action@v2
            with:
              cache-read-only: false
          - name: Install Python
            uses: actions/setup-python@v4
            with:
              python-version: '3.8'
          - name: Set up Cloud SDK
            uses: google-github-actions/setup-gcloud@v1
          - name: run website_stageWebsite script
            run: ./gradlew :website:stageWebsite